[package]
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
name = "rrinlog-server"
version = "0.1.0"

[dependencies]
env_logger = "0.4.3"
failure = "0.1.1"
itertools = "0.7.2"
log = "0.3.8"
actix = "0.7"
serde = "1.0.21"
serde_derive = "1.0.21"
serde_json = "1.0.6"
structopt = "0.2"

[dependencies.actix-web]
version = "0.6"
default-features = false

[dependencies.uom]
version = "0.20.0"
features = ["i64", "si"]

[dependencies.chrono]
features = ["serde"]
version = "0.4.0"

[dependencies.diesel]
features = ["sqlite"]
version = "1"

[dependencies.rrinlog_core]
path = ".."
