[package]
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
name = "rrinlog-server"
version = "0.1.0"

[dependencies]
env_logger = "0.6.0"
failure = "0.1.4"
itertools = "0.8.0"
log = "0.4.6"
actix = "0.7"
serde = "1.0.82"
serde_derive = "1.0.82"
serde_json = "1.0.33"
structopt = "0.2"

[dependencies.actix-web]
version = "0.7"
default-features = false

[dependencies.uom]
version = "0.20.1"
features = ["i64", "si"]

[dependencies.chrono]
features = ["serde"]
version = "0.4.0"

[dependencies.diesel]
features = ["sqlite"]
version = "1"

[dependencies.rrinlog_core]
path = ".."
